### ISSUE TITLE
size of radar polar image

### ISSUE THREAD

**Issue by Refstop** [mttgdd/oord-dataset#1]
Hello,
Thank you for your effort to provide radar dataset.
As I downloaded Bellmouth dataset for place recognition, I got issue that size of few images was 399x7547.
In my experience, I checked most of radar datasets got 400xRange size polar image.
Is there some kind of issue in data processing or just the size of original data from sensor is 399?
I'm glad to check this issue for dataset users.
Best,

**Comment by mttgdd** [comment]
Hiya this is as per the Radar RobotCar Dataset (https://arxiv.org/pdf/1909.01300.pdf) where some packets are dropped.

<img width="539" alt="Screenshot 2024-04-06 at 11 08 02" src="https://github.com/mttgdd/oord-dataset/assets/3154919/7b18f760-3fb8-40ab-a045-3c3d29214708">

I have not handled this in this new release. I will have a think about this and arrange it programmatically in the SDK, soon.

**Comment by mttgdd** [comment]
In fact, the following in `dataset.py` resizes to a fixed size, which should achieve similar effect as interpolation

<img width="574" alt="Screenshot 2024-04-06 at 11 12 53" src="https://github.com/mttgdd/oord-dataset/assets/3154919/5043ea35-59d1-4067-a6fb-38afb212653e">
